[versions]
spigot = "1.8.8-R0.1-SNAPSHOT"

[libraries]
spigot = { group = "org.spigotmc", name = "spigot-api", version.ref = "spigot" }
vault = { group = "com.github.MilkBowl", name = "VaultAPI", version = "1.7" }

[plugins]
minecrell = {id = "net.minecrell.plugin-yml.bukkit", version = "0.5.2"}